"""ASEKO ASIN AQUA Home integration."""

from __future__ import annotations

import logging

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers import entity_registry as er

from .const import (
    CONF_FORWARD_ENABLED,
    CONF_WATER_LEVEL_OFFSET,
    DEFAULT_CAPTURE_ENABLED,
    DEFAULT_FORWARD_ENABLED,
    DEFAULT_FORWARD_HOST,
    DEFAULT_FORWARD_PORT,
    DEFAULT_LISTEN_HOST,
    DEFAULT_LISTEN_PORT,
    DEFAULT_MAX_CHLORINE,
    DEFAULT_PROTOCOL_DEBUG,
    DEFAULT_WATER_LEVEL_OFFSET,
    DEVICE_IDENTIFIER,
    DOMAIN,
    PLATFORMS,
)
from .coordinator import AsekoCoordinator
from .dosing_tracker import DOSING_CHANNELS

_LOGGER = logging.getLogger(__name__)

_RELOAD_OPTION_KEYS = {
    "listen_host",
    "listen_port",
    "forward_host",
    "forward_port",
    "max_chlorine",
    CONF_WATER_LEVEL_OFFSET,
}


def _options(entry: ConfigEntry) -> dict:
    values = {**entry.data, **entry.options}
    options = {
        "listen_host": values.get("listen_host", DEFAULT_LISTEN_HOST),
        "listen_port": values.get("listen_port", DEFAULT_LISTEN_PORT),
        "forward_enabled": values.get("forward_enabled", DEFAULT_FORWARD_ENABLED),
        "forward_host": values.get("forward_host", DEFAULT_FORWARD_HOST),
        "forward_port": values.get("forward_port", DEFAULT_FORWARD_PORT),
        "protocol_debug": values.get("protocol_debug", DEFAULT_PROTOCOL_DEBUG),
        "capture_enabled": values.get("capture_enabled", DEFAULT_CAPTURE_ENABLED),
        "max_chlorine": values.get("max_chlorine", DEFAULT_MAX_CHLORINE),
        "water_level_offset": values.get(
            CONF_WATER_LEVEL_OFFSET,
            DEFAULT_WATER_LEVEL_OFFSET,
        ),
    }
    for channel in DOSING_CHANNELS:
        options[f"{channel.key}_container_size"] = values.get(
            f"{channel.key}_container_size", channel.container_size_default
        )
        options[f"{channel.key}_flow_rate"] = values.get(
            f"{channel.key}_flow_rate", 0.0
        )
    return options


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    await _async_migrate_duplicated_prefix_entity_ids(hass, entry)
    coordinator = AsekoCoordinator(hass, entry.entry_id, _options(entry))
    await coordinator.async_start()
    hass.data.setdefault(DOMAIN, {})[entry.entry_id] = coordinator
    entry.async_on_unload(entry.add_update_listener(_reload))
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
    return True


async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    if unload := await hass.config_entries.async_unload_platforms(entry, PLATFORMS):
        await hass.data[DOMAIN].pop(entry.entry_id).async_stop()
    return unload


async def _reload(hass: HomeAssistant, entry: ConfigEntry) -> None:
    coordinator = hass.data[DOMAIN][entry.entry_id]
    new_options = _options(entry)
    changed_options = {
        key
        for key, value in new_options.items()
        if coordinator.options.get(key) != value
    }
    if changed_options & _RELOAD_OPTION_KEYS:
        await hass.config_entries.async_reload(entry.entry_id)
        return
    coordinator.options.update(new_options)
    if CONF_FORWARD_ENABLED in changed_options:
        await coordinator.async_set_forwarding_enabled(
            new_options[CONF_FORWARD_ENABLED]
        )


async def _async_migrate_duplicated_prefix_entity_ids(
    hass: HomeAssistant, entry: ConfigEntry
) -> None:
    """Rename only known generated duplicated-prefix registry entity IDs."""
    registry = er.async_get(hass)
    for platform, key in _known_semantic_entity_keys():
        old_entity_id = f"{platform}.{DEVICE_IDENTIFIER}_{DEVICE_IDENTIFIER}_{key}"
        new_entity_id = f"{platform}.{DEVICE_IDENTIFIER}_{key}"
        old_entry = registry.async_get(old_entity_id)
        if old_entry is None:
            continue
        if getattr(old_entry, "config_entry_id", entry.entry_id) != entry.entry_id:
            continue
        if getattr(old_entry, "platform", DOMAIN) != DOMAIN:
            continue
        expected_unique_id = f"{DEVICE_IDENTIFIER}_{key}"
        unique_id = getattr(old_entry, "unique_id", None)
        # Unique IDs were already stable; only migrate entries we can prove were
        # generated by this integration rather than arbitrary user customizations.
        if unique_id is not None and unique_id != expected_unique_id:
            continue
        if registry.async_get(new_entity_id) is not None:
            _LOGGER.warning(
                "Skipping ASEKO entity ID migration from %s to %s because the target entity ID already exists",
                old_entity_id,
                new_entity_id,
            )
            continue
        registry.async_update_entity(old_entity_id, new_entity_id=new_entity_id)


def _known_semantic_entity_keys() -> tuple[tuple[str, str], ...]:
    """Return keys for entities generated by this integration."""
    from .binary_sensor import DESCRIPTIONS as BINARY_SENSOR_DESCRIPTIONS
    from .button import BUTTON_DESCRIPTIONS
    from .number import DESCRIPTIONS as NUMBER_DESCRIPTIONS
    from .sensor import DESCRIPTIONS as SENSOR_DESCRIPTIONS
    from .switch import CLOUD_FORWARDING_DESCRIPTION

    return (
        *(("sensor", description.key) for description in SENSOR_DESCRIPTIONS),
        *(
            ("binary_sensor", description.key)
            for description in BINARY_SENSOR_DESCRIPTIONS
        ),
        *(("number", description.key) for description in NUMBER_DESCRIPTIONS),
        ("switch", CLOUD_FORWARDING_DESCRIPTION.key),
        *(("button", description.key) for description in BUTTON_DESCRIPTIONS),
    )
